<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <RunAOTCompilation>true</RunAOTCompilation>
        <InvariantGlobalization>true</InvariantGlobalization>

        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>

        <PublishTrimmed>true</PublishTrimmed>
        <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
        <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
        <DebuggerSupport>false</DebuggerSupport>
        <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
        <EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>
        <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
        <InvariantGlobalization>true</InvariantGlobalization>
        <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
        <MetricsSupport>false</MetricsSupport>
        <StackTraceSupport>false</StackTraceSupport>
        <OptimizationPreference>Size</OptimizationPreference>
        <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
        <IlcTrimMetadata>true</IlcTrimMetadata>
        <IlcDisableReflection>true</IlcDisableReflection>
        <IlcOptimizationPreference>Size</IlcOptimizationPreference>
        <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
    </PropertyGroup>

</Project>
